Module4 task3
htmlacademy-adaptive/1309675-cat-energy-21 pull request #10
Opened 2021-01-17 23:46 UTC by alexander-morozov-travelline

2021-01-18 17:29 UTC, avylando requested changes
Что осталось сделать:
- Поправить верстку списка товаров (гриды или правильные отступы)
- Блок `cooperation` на десктопе
- Горизонтальный скролл на мобилке (в каталоге тоже)
- Доделать футер
- Остальные минорные правки, включая два предыдущих задания
![Снимок2](https://user-images.githubusercontent.com/30809044/104946793-80972b80-59dc-11eb-8ccb-6724fe6b3683.PNG)

2021-01-18 17:29 UTC, avylando commented on source/sass/blocks/button.scss
> +  &--catalog {
Не самый лучший выбор названия для модификатора) Лучше привязывать название к внешнему виду кнопки, а не к блокам или страницам. Например `button--wide` или `button--big` Т.к. у тебя такая кнопку теоретически может где угодно использоваться

2021-01-18 17:29 UTC, avylando commented on source/sass/blocks/catalog.scss
> +  }
Тут ты зря игнорируешь гриды, для таких раскладок они намного удобнее флексов. Тогда тебе не нужно будет мучиться с маргинами так как там отступы удобно задаются через grid-gap. Но если ты хочешь оставить на флексах, то тут нужно разобраться с отступами, убрать отрицательные маргины (и вообще обращаться к ним как можно реже), а вместо этого задать правильные отступы для catalog__item

2021-01-18 17:29 UTC, avylando commented on source/catalog.html
>        </div>
Нужно еще сделать позиционирование этого блока на десктопной версии

2021-01-19 14:42 UTC, avylando reviewed
Принимаю, в основном все ок
Поправь еще вот этот косяк с заголовком в следующем пулле
![Снимок](https://user-images.githubusercontent.com/30809044/105049380-66b62100-5a8e-11eb-9fd5-3a475ca59d28.PNG)

2021-01-19 14:42 UTC, avylando commented on source/form.html
> +        <div class="padge-footer__wrap">
Опечатка paDge

2021-01-19 14:42 UTC, avylando commented on source/sass/blocks/page-footer.scss
> +.padge-footer__wrap {
Или там была не опечатка?) В любом случае нужно поправить чтобы было по БЭМ

2021-01-19 14:42 UTC, merged

2021-01-19 14:44 UTC, alexander-morozov-travelline commented on source/form.html
> +        <div class="padge-footer__wrap">
ага это опечатка

2021-01-19 14:45 UTC, alexander-morozov-travelline commented on source/sass/blocks/page-footer.scss
> +.padge-footer__wrap {
нет это опечатка

2021-01-19 14:45 UTC, alexander-morozov-travelline commented
А баг выше, это видимо при мерже конфликтов выскочил