Module2 task2
htmlacademy-adaptive/1309675-cat-energy-21 pull request #3
Opened 2020-12-04 17:24 UTC by alexander-morozov-travelline

2020-12-05 21:30 UTC, avylando requested changes

2020-12-05 21:30 UTC, avylando commented on source/form.html
> +    <footer class="page-footer">
Вижу шапку и футер, а где собственно контент страницы?)

2020-12-05 21:31 UTC, avylando commented
Нужно разметить содержимое страницы формы

2020-12-07 06:16 UTC, alexander-morozov-travelline commented
Извиняюсь, видимо что-то не правильно смержил, в локальной копии все есть, сегодня выложу.

From: Anatoly Dolgov <notifications@github.com>
Sent: Sunday, December 6, 2020 12:30 AM
To: htmlacademy-adaptive/1309675-cat-energy-21 <1309675-cat-energy-21@noreply.github.com>
Cc: Александр Морозов <alexander.morozov@travelline.ru>; Author <author@noreply.github.com>
Subject: Re: [htmlacademy-adaptive/1309675-cat-energy-21] Разметка страницы формы (#3)


@avylando requested changes on this pull request.

________________________________

In source/form.html<https://github.com/htmlacademy-adaptive/1309675-cat-energy-21/pull/3#discussion_r536896062>:

> +    </header>







+    <footer class="page-footer">



Вижу шапку и футер, а где собственно контент страницы?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/htmlacademy-adaptive/1309675-cat-energy-21/pull/3#pullrequestreview-545651016>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APJ5KBXLWXG6W2KFRVQAHR3STKQ6NANCNFSM4UNXAESA>.

2020-12-07 10:51 UTC, alexander-morozov-travelline commented
Все теперь должно быть, посмотрел отображается
https://htmlacademy-adaptive.github.io/1309675-cat-energy-21/3/form.html
Из первой задачи тоже подправил замечания.

2020-12-08 11:54 UTC, avylando approved these changes
Привет! В основном все ок, не вижу ничего критичного, но то что есть прошу поправить далее

2020-12-08 11:54 UTC, avylando commented on source/form.html
> +      <hr class="form__line">
Линии делать hr не нужно, их потом будем делать через css

2020-12-08 11:54 UTC, avylando commented on source/form.html
> +        <fieldset class="checkbox__list">
Лучше поменять местами fieldset и div,  особенно есть form__checkbox задумывается как флекс-контейнер
А если это list, то логично вообще использовать не div,  а ul)

2020-12-08 11:54 UTC, avylando commented on source/form.html
> +      <label class="label form__label">Возраст (лет): <input class="input form__input" type="text" name="age" value="7"></label>
В инпутах вместо value используй placeholder, value - это не очень хорошо для пользователя и при валидации формы

2020-12-08 11:54 UTC, avylando commented on source/form.html
> +      <button class="form__button button">отправить заявку</button>
У button нужно явно прописать атрибут type

2020-12-08 11:54 UTC, avylando commented on source/form.html
> +      <span class="form__notice">* — Обязательные поля</span>
Тут span явно недостаточно, на макете это выглядит как блочный элемент

2020-12-08 11:54 UTC, avylando commented on source/form.html
> +      <span class="cooperation__address">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</span>
Это тоже блочные элементы

2020-12-08 11:54 UTC, avylando commented on source/index.html
> +        <h2 class="promo__title">Функциональное питание для котов</h2>
Тут как-то задвоилось у тебя, ничего страшного если h1 будет заголовком секции
Это лучше чем дублировать элементы

2020-12-08 11:55 UTC, merged