Стилизация главной страницы
htmlacademy-adaptive/1309675-cat-energy-21 pull request #5
Opened 2020-12-11 16:45 UTC by alexander-morozov-travelline

2020-12-21 17:45 UTC, alexander-morozov-travelline commented
Отображается немного не по макету.
Не совсем понял какие нужны пути для шрифтов:
Пробовал вот так: /fonts/oswaldmedium.woff - так работает на локальном
Пробовал ./fonts/oswaldmedium.woff - так не работает ни на локальном ни на опубликованном.

2020-12-23 09:41 UTC, avylando requested changes
Привет! Из того что критично  - нужно правильно задать шрифты и убрать лишние глобальные стили
Дополнительно - вынести цвета в переменные, а группы повторяющихся свойств в миксины

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/advantages.scss
> +  padding: 0;
Эти стили можно вынести в миксин и использовать для сброса стандартных стилей списка (он тебе пригодится еще не раз)

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/button.scss
> +  font-family: "Oswald", sans-serif;
Это основной шрифт всего макета, его нужно указать для body + добавить промежуточный веб-безопасный шрифт из того же семейства

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/cooperation.scss
> +  font-family: "Oswald", sans-serif;
Шрифт задается через body и наследуется всеми элементами
Если нужно переопределить его, то переопределяем точечно

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/cooperation.scss
> +  color: #444444;
Цвета нужно вынести в переменные

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/cooperation.scss
> +  color: #111111;
Цвета нужно вынести в переменные

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/main-nav.scss
> +  padding: 0;
Здесь можно использовать миксин сброса стилей списка

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/progress.scss
> +}
тут тоже

2020-12-23 09:41 UTC, avylando commented on source/sass/blocks/progress.scss
> +    background-image: url("data:image/svg+xml,%3Csvg width='24' height='12' viewBox='0 0 24 12' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cline y1='6' x2='18' y2='6' stroke='black' stroke-wi
тут нужно указать нормальный путь к файлу, а не использовать кодировку через data:type

2020-12-23 09:41 UTC, avylando commented on source/sass/fonts.scss
> +    url("../fonts/oswaldmedium.woff2") format("woff");
Здесь все верно, шрифты у тебя подключились
Но они не везде применились, т.к. они не заданы body (писал выше)

2020-12-23 09:41 UTC, avylando commented on source/sass/global.scss
> +}
Этот файл нарушает критерий https://up.htmlacademy.ru/adaptive/21/criteries#d16
Лучше используй стандартный normalize

2020-12-23 14:33 UTC, alexander-morozov-travelline commented
Все исправил, но есть один момент со стилем normolize.css.
Я сего скачал засунул в папку css и подключил вместе со всеми стилями
<link href="./css/normalize.css" rel="stylesheet">
<link href="./css/style.css" rel="stylesheet">
Но в проекте вся папка css стоит в gitignore, и тут не понятно что делать:

- либо исключать файл normalize.css из gitignore
- либо засунуть его в другую локацию
- либо подключать его в scss, но тут тоже не совсем понятно как

2020-12-24 08:03 UTC, alexander-morozov-travelline commented
Все подправил

2020-12-25 08:34 UTC, avylando commented on source/sass/blocks/advantages.scss
> +$advantagesTextColor: #444444;
Есть хорошая практика выносить все переменные в один файл - variables.scss.
Иначе у тебя получается дублирование одного и того же цвета в разных файлах под разными названиями. А в макете, как правило, есть набор фирменных цветов, которые применяются во всех блоках, поэтому их и удобно унифицировать внутри одного файла. Таким образом, в будущем легко можно изменить один цвет, поменяв значение только одной переменной

2020-12-25 08:35 UTC, avylando commented on source/sass/blocks/button.scss
> +$buttonColor: #ffffff;
Названия переменных лучше привязывать не к элементам, а к цветам - `$white: #ffffff`
Так намного понятнее

2020-12-25 08:36 UTC, avylando commented on source/sass/global.scss
> +  list-style: none;
Миксины тоже лучше вынести в отдельный файл mixins

2020-12-25 08:39 UTC, avylando reviewed
Задание принимаю с оговорками
- Не подгрузился normalize. Я написал тебе как это можно исправить
- Есть вопросы к структуре - прими во внимание

2020-12-25 08:40 UTC, merged