Module4 task1
htmlacademy-adaptive/1309675-cat-energy-21 pull request #8
Opened 2021-01-15 08:29 UTC by alexander-morozov-travelline

2021-01-16 15:34 UTC, avylando requested changes
Привет! Нужно поправить замечания, добавить контейнеры и поправить сетки
Проверял только сетки, не очень понятно в какой именно стадии находятся страницы каталога и формы, но в рамках этого пулла главное исправить ошибки на главной

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/example.scss
>  }
Мне кажется, тут у тебя два практически одинаковых элемента вложенных друг в друга
Если есть возможность, то лучше избавляться от избыточных. Здесь есть ощущение что обе обертки делают одно и то же

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/example.scss
>  .example {
В этом блоке на десктопе сетка не соответствует макету
![Снимок2](https://user-images.githubusercontent.com/30809044/104815464-92d76500-5836-11eb-88da-c89df6f85126.PNG)

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/form.scss
>  .form {
у формы сетка не соответствует макету:
на планшете
![Снимок3](https://user-images.githubusercontent.com/30809044/104815640-a0d9b580-5837-11eb-9c01-445aefc0bf7f.PNG)

на десктопе
![Снимок5](https://user-images.githubusercontent.com/30809044/104815654-adf6a480-5837-11eb-8885-8031f7bed082.PNG)

на мобилке появляется горизонтальный скролл
![Снимок4](https://user-images.githubusercontent.com/30809044/104815663-b4851c00-5837-11eb-8a2b-e22773028b2a.PNG)

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/progress.scss
> +      margin-top: 31px;
Тут неровные отступы
![Снимок6](https://user-images.githubusercontent.com/30809044/104815751-42610700-5838-11eb-8513-c5548e516d71.PNG)

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/section.scss
>    font-size: 36px;
Тут название файла не соответствует названию блока

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/site-list.scss
> +    margin: 0 0 0 32px;
Сокращенные свойства понимать сложнее, старайся использовать подробные (right, left, top, bottom), особенно в таких случаях

2021-01-16 15:34 UTC, avylando commented on source/sass/blocks/site-list.scss
> +      }
Этот элемент не отцентрирован, используй тот же прием с transform: translate

2021-01-16 15:34 UTC, avylando commented on source/sass/variables.scss
> +$mobileOnly: 767px;
Мобильная ширина у нас 320px, лучше храни это значение в переменных

2021-01-16 15:34 UTC, avylando commented on source/sass/variables.scss
> +$desktop: 1200px;
Десктопная ширина Cat-energy 1440px

2021-01-17 08:26 UTC, alexander-morozov-travelline commented on source/sass/variables.scss
> +$desktop: 1200px;
Десктопная ширина 1440 - да знаю, но это не мешает перестраивать страницу раньше, тем более в лекции об этом говорили

2021-01-17 09:49 UTC, alexander-morozov-travelline commented on source/sass/variables.scss
> +$desktop: 1200px;
Тоже и для мобильной версии, верстаю да для 320 - как минимальное разрешение, перестраивать начинаю с 768, вообще не знаю зачем хранить значение 320.

2021-01-17 10:42 UTC, avylando commented on source/sass/variables.scss
> +$desktop: 1200px;
Как минимум для тоже чтобы знать минимальную ширину своей верстки.
А вот зачем хранить переменную `$mobileOnly: 767px` - не понятно. Если тебе где-то нужно знать максимальную ширину на мобилке то ты всегда можешь вычислить `#{$tablet - 1}px`

2021-01-17 10:59 UTC, alexander-morozov-travelline commented on source/sass/blocks/example.scss
>  }
да они похоже но в разных разрешениях они по разному элементы выстраивают в одном случае в колонке в другом в   ряды

2021-01-17 15:02 UTC, alexander-morozov-travelline commented on source/sass/blocks/example.scss
>  }
Немного подправил, немного да напутал.

2021-01-18 14:14 UTC, avylando approved these changes
Замечания исправлены

2021-01-18 14:14 UTC, avylando commented on source/sass/blocks/advantages.scss
> +    margin-bottom: -28px;
Если есть возможность, не используй отрицательный маргин, т.к. это он немного усложняет понимание. В этом месте точно можно обойтись без него

2021-01-18 14:14 UTC, merged

2021-01-19 05:43 UTC, alexander-morozov-travelline commented on source/sass/blocks/advantages.scss
> +    margin-bottom: -28px;
В данном случае отрицательный марджин, чтобы скомпенсировать марджины от отдельных элементов

2021-01-19 09:22 UTC, avylando commented on source/sass/blocks/advantages.scss
> +    margin-bottom: -28px;
Я понимаю для чего он, но это плохое решение
Здесь просто нужно определить правильные отступы соседних элементов